# Decap CMS config for the Astro portfolio site
backend:
  name: github
  repo: iqbard/website-portfolio
  branch: main
  commit_messages:
    create: "Create {{collection}} "
    update: "Update {{collection}} "
    delete: "Delete {{collection}} "

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "work"
    label: "Work"
    folder: "src/content/work/nested"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Image", name: "img", widget: "image", required: false}
      - {label: "Image alt", name: "img_alt", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}